language: common-lisp
sudo: false

#from https://github.com/roswell/roswell/wiki/Travis-CI

addons:
  apt:
    packages:
      - libc6-i386
      - openjdk-7-jre

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl-bin COVERALLS=true
#    - LISP=abcl
#    - LISP=ecl
#    - LISP=alisp
#    - LISP=cmucl
#    - LISP=clisp
#    - LISP=ccl-bin

matrix:
  fast_finish: true

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh

script:
  - ros -s fiveam -s cl-coveralls -e "
             (coveralls:with-coveralls (:exclude \"t\")
                 (unless (5am:run! (intern \"LINEAR-PROGRAMMING\" :linear-programming-test/all))
                     (uiop:quit 1)))"
