language: generic

#from https://github.com/roswell/roswell/wiki/Travis-CI

addons:
  homebrew:
    update: true
    packages:
    - roswell
  apt:
    packages:
      - libc6-i386
      - default-jre

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  jobs:
    - LISP=sbcl-bin COVERALLS=true DOCS=true
    - LISP=abcl
    - LISP=ecl
    - LISP=alisp
    - LISP=ccl-bin
    - LISP=cmucl
#    - LISP=clisp #fails to download

jobs:
  fast_finish: true
  include:
    - os: osx
      env: LISP=sbcl-bin
    - os: osx
      env: LISP=ccl-bin

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

install:
  - curl -L https://raw.githubusercontent.com/roswell/roswell/release/scripts/install-for-ci.sh | sh
  - ros install neil-lindquist/ci-utils
  - ros install neil-lindquist/doc-site-generator
  # CCL's default asdf is slightly too old, so need to use a newer version
  - mkdir -p ~/common-lisp
  - if [ "$LISP" == "ccl-bin" ]; then git clone https://gitlab.common-lisp.net/asdf/asdf.git ~/common-lisp; fi

script:
  - run-fiveam -e t -l linear-programming-test linear-programming-test:linear-programming

before_deploy:
  - copy-site-base docs docs-bin
  - echo "The documentation page for the linear-programming Common Lisp library." | make-gh-page README.md docs-bin/index.md
  - script/generate-API-docs.ros

deploy:
  provider: pages
  skip_cleanup: true
  token: $GITHUB_TOKEN
  keep_history: true
  local_dir: docs-bin
  on:
    branch: master
    condition: $DOCS = true
