# --- General options --- #

baseurl: "/linear-programming"

# Name of website
title: linear-programming

# Short description of your site
description: Documentation for the linear-programming Common Lisp Library

# --- Navigation bar options --- #

# List of links in the navigation bar
navbar-links:
  API Documentation: "API"
  DSL Syntax: "linear-problem-syntax"

# Image to show in the navigation bar - image must be a square (width = height)
# Remove this parameter if you don't want an image in the navbar
# avatar: "/img/avatar.png"

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
# title-img: /path/to/image

# --- Footer options --- #

# Select your active Social Network Links.
# Uncomment the links you want to show in the footer and add your information to each link.
# You can reorder the items to define the link order.
# If you want to add a new link that isn't here, you'll need to also edit the file _data/SocialNetworks.yml
social-network-links:
  email: "neillindquist5@gmail.com"
  public-key: "/neil-lindquist-public-key.pgp"
  github: neil-lindquist/linear-programming
#  linkedin: neil-lindquist
#  orcid: 0000-0001-9404-3121
#  rss: true
#  facebook: daattali
#  twitter: daattali
#  reddit: yourname
#  xing: yourname
#  stackoverflow: "3943160/daattali"
#  snapchat: deanat78
#  instagram: deanat78
#  youtube: user/deanat78
#  spotify: yourname
#  telephone: +14159998888
#  steam: deanat78
#  twitch: yourname
#  yelp: yourname


# Exclude these files from production site
exclude:

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: false # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: false
